### PR TITLE
added data table matcher

### LINKED ISSUE #51: Data Table Matcher
I'd suggest a data table matcher. Currently for our implementation we're using this

```
/* 
	Class: UtEqualToDataTableMatcher
		---Prototype---
		class UtEqualToDataTableMatcher inherits UtEqualToMatcher
		---------------
		
		Operates only on datatables. See <UtEqualToMatcher>.
*/
Define Class(
	"UtEqualToDataTableMatcher",
	Base Class( UtEqualToMatcher ),
	_init_ = Method({}, super:matches value = Name Expr( this:matches value ) );
	matches value = Method({actual},
		obj = actual << Compare Data Tables( compare With( this:value ) );
		
		If( !(obj << Are Data Different),
			::ut match info success();
		,
			mismatch = "was " || Char( actual );
			LRE = ::ut global lre( actual, this:value );
			::ut match info failure( mismatch, LRE );
		);
	);
);
```

but this doesn't take into account table variables, or scripts.  It just checks that the data are the same.

### PR DESCRIPTION
**Pull request by VDFaller**
added a data table matcher
closes #51 
## Checklist
- [x] **I am adding a new matcher.**
  - [ ] I have included documentation with at least one example and description.
  - [ ] I have added tests in `Tests/UnitTests/Matchers`.
  - [ ] I have added matcher to `Source/Matchers-Index.txt`.
  - [ ] I have added a note to `CHANGELOG.md`.

## Contributing

- [x] I have read and agree to the [Contributor Agreement](https://github.com/sassoftware/jsl-hamcrest/blob/master/ContributorAgreement.txt)

Signed-off-by: Vince Faller <Vince.Faller@predictum.com>

### CODE REVIEW

**Comment by VDFaller** [comment]
So I definitely don't understand your documentation.  My apologies.  I don't see similar documentation for any of the other `EqualTo` matchers.

**Comment by JustinChilton** [comment]
So the examples in the documentation are meant for matcher factories and not necessarily the class definitions. All you really need for the class definitions is the name, what it inherits from, and a short description, all of which you have. Since you are adding additional functionality to an existing matcher (equal to), there is not much need for additional examples.

We probably want to discuss whether we want to use the Compare Data Tables platform or if there is a cleaner and clearer way to assert that two data tables are the same. Getting the column values as a list and comparing should be fairly efficient? 

There is also the issue of what is considered equal, just the data, or do the scripts and table properties need to be the same? Maybe we should consider making these separate matchers, such as `ut table data` and `ut table scripts` that assert that certain aspects of two data tables are the same.

**Comment by VDFaller** [comment]
@JustinChilton What about if we did something like this 
```jsl
Names default to here(1);
dt = open("$SAMPLE_DATA\Big Class.jmp");
dt << Save As("$TEMP\Big Class 2.jmp");
dt2 = open("$TEMP\Big Class 2.jmp");
dt = open("$SAMPLE_DATA\Big Class.jmp");
script = dt << Get script();
script2 = dt2 << Get Script();
// this is only to deal with the fact that sometimes JMP automatically appends a 2 to tables with the same name
substitute into(script, dt << Get Name, "DONTWORRYABOUTIT");
substitute into(script2, dt2 << Get Name, "DONTWORRYABOUTIT");

show(nameexpr(script) == nameexpr(script2));
```

This would be the most "equal" they could be. Row states, column properties and all.

**Comment by JustinChilton** [comment]
I think if you are going to compare all of the properties of a data table, we should be doing each part independently so we can tell the user exactly where the difference was. I also don't love the comparing of tables scripts because you cannot control how much you want to compare. It could fail for any reason, even something trivial like a column's display width.

If we were to compare the tables piece by piece, we have the ability to have options to ignore certain things like table scripts. This would also enable us to improve performance when there is an obvious difference, like a different number of columns or column name differences. We could order our checks in such a way that does faster operations first, and slow things like comparing data values last.

One matcher that accepts a list of options is [ut approx](https://github.com/sassoftware/jsl-hamcrest/blob/master/Source/Matchers/Approx.jsl#L197). We could do something similar for data tables, with options like `Table Scripts( 0 | 1 )`, `Table Variables( 0 | 1 )`, `Column Names( 0 | 1 )`, etc. We could also add matcher factories that automatically set the options for you, such as `ut table scripts` which could only compare tables scripts or `ut table data` which could just compare data.

**Comment by VDFaller** [comment]
That's way better.  I'll see if I can start writing some.

**Comment by nrclark38258** [comment]
I am curious how this is going. I'm excited to use it. I have created my own ut test()s for comparing whole data tables, but it's basically just surfing the report for "no difference" text. If it matches, awesome, but if they don't I have to go through manually to find differences - still better than coding lots of individual tests :)

**Comment by emccorkle** [comment]
I'm working on some individual matchers that cover parts of columns, parts of tables, etc. Then hopefully I can compose these together to make a more informative matcher for entire tables.

**Comment by VDFaller** [comment]
Closing this as it won't get merged in.

**Pull request closed without merging**
