### PR TITLE
Add junit xml reporter

### LINKED ISSUE #56: JUnit Reporter
I'd like to have a reporter for JUnit.  We've already created it.  Would you recommend putting it in reporters or the new custom folder?

### PR DESCRIPTION
**Pull request by dougiechong**
creates a reporter that inherits from ut collecting reporter.
takes the failures/successes and parses by the arrow.
Report comes out in XML format found in the comment of the class

## Description

This is a copy of PR #60 that was closed accidentally and could not be reopened

closes #56

## Checklist

- [x] **I am adding a new reporter.**
  - [x] I have included documentation with at least one example and description.
  - [x] I have added tests in `Tests/UnitTests/Reporters`.
  - [x] I have added a note to `CHANGELOG.md`.

- [x] **I am adding new or changing current functionality.**
  - [x] I have added or updated the tests for the new or changed functionality in `Tests/UnitTests`.
  - [x] I have added note(s) to `CHANGELOG.md` as necessary.

## Contributing

- [x] I have read and agree to the [Contributor Agreement](https://github.com/sassoftware/jsl-hamcrest/blob/master/ContributorAgreement.txt)

Signed-off-by: Douglas Chong <dougiechong@gmail.com>

### CODE REVIEW

**Comment by emccorkle** [comment]
I have run the output of this reporter through the Jenkins JUnit plugin. I used a file with tests cases, anonymous assertions, passing, failing, and error-ing. They all seemed to parse fine and the report looked reasonable.

I'm approving this, however, I think there are some potential improvements. I have listed some below. I'll leave it up to you to merge and I'll let you decide if you would like to address any of the below in this PR (before merging) or simply defer them into GitHub issue(s). If you want to address any now, Justin and I will be available for more reviews.

### High-Priority
- [ ] Use `message` attribute rather than node contents for failure message (message vs stack trace, Jenkins reports this better)
- [ ] Possibly report one `junit testcase` per `ut test` rather than one per assertion (report can look busy now if there are multiple failures within a single `ut test`)

### Medium-Priority
- [ ] Added test timings (see also #52, may require reporting one per `ut test` change above)
- [ ] Customization of `_` between test name, assertion label, and assertion number
- [ ] Support for `error` in addition to `failure` (Jenkins may not make a distinction though)

### Low-Priority
- [ ] Report tests in the order they are run rather than in alphabetical order (Jenkins may not make a distinction through)
- [ ] Support for skipped tests (would require change to test and reporter APIs)

**Review by emccorkle — APPROVED** [review]

**Comment by dougiechong** [comment]
@emccorkle, I think this PR is already too long, and will defer the other items to separate github issues.

Thank you for all your help, making the reporter report per ut test instead of assertion will probably be the next issue I work on.

**Comment by dougiechong** [comment]
@emccorkle, I have added new issues for the improvements I will likely do in the future. Is there a reason why this PR has not been merged and closed yet?

**Comment by JustinChilton** [comment]
I think @emccorkle thought you could see a button that says "Merge pull request" now that it is approved. Is that not the case? If not, I can merge it for you.

**Comment by dougiechong** [comment]
@JustinChilton, it would be great if you could merge it.

I get the following message:

"Only those with write access to this repository can merge pull requests."

**Pull request merged**
